version: '3.4'

services:
  daprdockertester:
    image: ${DOCKER_REGISTRY-}daprdockertester
    build:
      context: .
      dockerfile: DaprDockerTester/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - hello-dapr

  daprdockertester-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "daprdockertester", 
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - daprdockertester
    network_mode: "service:daprdockertester"

  daprdockerbackend:
    image: ${DOCKER_REGISTRY-}daprdockerbackend
    build:
      context: .
      dockerfile: DaprDockerBackend/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - hello-dapr

  daprdockerbackend-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "daprdockerbackend", 
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - daprdockerbackend
    network_mode: "service:daprdockerbackend"

  ############################
  # Dapr placement service
  ############################
  #placement:
  #  image: "daprio/dapr"
  #  command: ["./placement", "-port", "50006"]
  #  ports:
  #    - "50006:50006"
  #  networks:
  #    - hello-dapr
  ############################
  # Redis state store
  ############################
  redis:
    container_name: "redis_service"
    image: "redis:alpine"
    ports:
      - "6379"
    networks:
      - hello-dapr
  zipkin:
    container_name: "zipkin_service"
    image: openzipkin/zipkin # https://registry.hub.docker.com/r/openzipkin/zipkin
    ports:
      - 9412:9411
    networks:
      - hello-dapr
networks:
    hello-dapr: