# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  daprfunctester:
    image: daprfunctester
    container_name: "daprfunctester"
    build:
      context: .
      dockerfile: DaprFuncTester/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
#    networks:
#      - hello-dapr

  daprfunctester-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "daprfunctester", 
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - daprfunctester
        - redis
    network_mode: "service:daprfunctester"


  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
#    networks:
#      - hello-dapr
  ############################
  # Redis state store
  ############################
  redis:
    container_name: "redis_service"
    image: "redis:alpine"
    ports:
      - "6379"
#    networks:
#      - hello-dapr
  zipkin:
    container_name: "zipkin_service"
    image: openzipkin/zipkin # https://registry.hub.docker.com/r/openzipkin/zipkin
    ports:
      - 9412:9411
#    networks:
#      - hello-dapr
  azurestorage.emulator:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    container_name: "azurite_service"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
#    networks:
#      - hello-dapr
#networks:
#    hello-dapr: