version: '3.4'

services:
  #daprdockertester:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "80"
  #daprdockerbackend:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "80"
  functiondurable:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  pdfgenerator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  docgendispatcher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  fenicsdispatcher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  daprfunctester:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
