version: '3.4'

services:
  functiondurable:
    image: ${DOCKER_REGISTRY-}functiondurable
    build:
      context: .
      dockerfile: FunctionDurable/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
      - AzureWebJobsStorage
      - WEBSITE_HOSTNAME
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc 
    ports:
      - 7071:80
    volumes:
      - sidecar-volume:/kerberos-sidecar:ro 
    networks:
      - hello-dapr

  functiondurable-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "functiondurable", 
     "-app-port", "3001",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - functiondurable
    network_mode: "service:functiondurable"

  pdfgenerator:
    image: ${DOCKER_REGISTRY-}pdfgenerator
    build:
      context: .
      dockerfile: PdfGenerator/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
      - AzureWebJobsStorage
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc 
    ports:
      - 7072:80
    volumes:
      - sidecar-volume:/kerberos-sidecar:ro 
    networks:
      - hello-dapr

  pdfgenerator-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "pdfgenerator", 
     "-app-port", "3001",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - pdfgenerator
    network_mode: "service:pdfgenerator"

  docgendispatcher:
    image: ${DOCKER_REGISTRY-}docgendispatcher
    build:
      context: .
      dockerfile: DocGenDispatcher/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
      - AzureWebJobsStorage
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc 
    ports:
      - 7073:80
    volumes:
      - sidecar-volume:/kerberos-sidecar:ro  
    networks:
      - hello-dapr

  docgendispatcher-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "docgendispatcher", 
     "-app-port", "3001",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - docgendispatcher
    network_mode: "service:docgendispatcher"

  fenicsdispatcher:
    image: ${DOCKER_REGISTRY-}fenicsdispatcher
    build:
      context: .
      dockerfile: FenicsDispatcher/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
      - AzureWebJobsStorage
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc 
    ports:
      - 7074:80
    volumes:
      - sidecar-volume:/kerberos-sidecar:ro 
    networks:
      - hello-dapr

  fenicsdispatcher-dapr:
    image: "daprio/daprd:1.8.0"
    command: [ "./daprd", 
     "-app-id", "fenicsdispatcher", 
     "-app-port", "3001",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ] 
    volumes:
        - "./SupportFiles/dapr/dc-components:/components" 
        - "./SupportFiles/dapr/dc-config:/config" 
    depends_on:
        - fenicsdispatcher
    network_mode: "service:fenicsdispatcher"


  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr
  ############################
  # Kerberos sidecar service
  ############################
  kerberos-sidecar:
    image: kerberos-sidecar
    hostname: kerberos-sidecar
    build:
      context: ./SupportFiles/krb
      dockerfile: Dockerfile
    environment:
      - SECRETS=/krb
      - KEYTAB=zhangm.keytab
      - PRINCIPAL=ZhangM
      - VOLUME=/kerberos-sidecar
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc
      - REKINIT_PERIOD=3600
      - TRACE_OUT=/dev/stdout
    volumes:
      - sidecar-volume:/kerberos-sidecar:rwx
    networks:
      - hello-dapr

  ############################
  # Redis state store
  ############################
  redis:
    container_name: "redis_service"
    image: "redis:alpine"
    ports:
      - "6379"
    networks:
      - hello-dapr
  zipkin:
    container_name: "zipkin_service"
    image: openzipkin/zipkin # https://registry.hub.docker.com/r/openzipkin/zipkin
    ports:
      - 9412:9411
    networks:
      - hello-dapr
  azurestorage.emulator:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    container_name: "azurite_service"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - hello-dapr
networks:
    hello-dapr:

volumes:
  sidecar-volume:
    name: kerberos-sidecar    